### ISSUE TITLE
Latest release tags not on Marketplace

### ISSUE THREAD

**Issue by rainest** [booxmedialtd/ws-action-parse-semver#24]
I was looking to clear the issue fixed by https://github.com/booxmedialtd/ws-action-parse-semver/releases/tag/v1.4.6, but it looks like the Marketplace version is still on https://github.com/booxmedialtd/ws-action-parse-semver/releases/tag/v1

Would it be possible to publish the latest version?

**Comment by tlangens** [comment]
Done
